# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zcache
%global goipath         zgo.at/zcache
%global forgeurl        https://github.com/zgoat/zcache
%global commit          df91dc43c1c80650ebcd2c23a13460efacc91204

%gometa

%global common_description %{expand:
An in-memory key:value store/cache (similar to Memcached) library for Go,
suitable for single-machine applications.}

%global golicenses      LICENSE
%global godocs          issue-list.markdown README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        An in-memory key:value store/cache (similar to Memcached) library for Go, suitable for single-machine applications

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/zcache %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc issue-list.markdown README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Fri Aug 28 16:50:12 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200828gitdf91dc4
- Initial package

