# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/ztest
%global goipath         zgo.at/ztest
%global forgeurl        https://github.com/zgoat/ztest
%global commit          3748d14cd472b6d1f1b4723cda581e1d8bf734b9

%gometa

%global common_description %{expand:
Small Go testing helpers.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Small Go testing helpers

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 10:56:22 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809git3748d14
- Initial package

