# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/zgoat/zvalidate
%global goipath         zgo.at/zvalidate
%global forgeurl        https://github.com/zgoat/zvalidate
%global commit          d3c7c37d330454dd74c9fbf041bc61fd7a44c444

%gometa

%global common_description %{expand:
Static validation for Go that returns parsed values.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Static validation for Go that returns parsed values

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(zgo.at/zstd/ztest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Jun 25 08:53:04 CEST 2021 Johan Kok <johan@fedoraproject.org> - 0-0.1.20210625gitd3c7c37
- Initial package

