# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zvalidate
%global goipath         zgo.at/zvalidate
%global forgeurl        https://github.com/zgoat/zvalidate
%global commit          5cb8e784f208aa5753185e7cdcce63d87692fd45

%gometa

%global common_description %{expand:
Static validation for Go that returns parsed values.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Static validation for Go that returns parsed values

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests
BuildRequires:  golang(zgo.at/ztest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 10:50:39 CEST 2020 Johan Kok <johan@fedoraproject.org> - 0-0.1.20200809git5cb8e78
- Initial package

