# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/errors
%global goipath         zgo.at/errors
%global forgeurl        https://github.com/zgoat/errors
%global commit          8255739ad6ec68969de26883c457d273e40ee0ed

%gometa

%global common_description %{expand:
Yet another errors package for Go.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Yet another errors package for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:11:53 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809git8255739
- Initial package

