# Generated by go2rpm 1
%bcond_without check

# https://git.sr.ht/~samwhited/otp
%global goipath         code.soquee.net/otp
%global forgeurl        https://git.sr.ht/~samwhited/otp
Version:                0.0.1

%gometa

%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE
%global godocs          CONTRIBUTING.md README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        None

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            %{gourl}
Source0:        https://git.sr.ht/~samwhited/otp/archive/v%{version}.tar.gz

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Sep 04 10:45:35 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0.0.1-1
- Initial package

