# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/gadget
%global goipath         zgo.at/gadget
%global forgeurl        https://github.com/zgoat/gadget
%global commit          64412137d778c43b9d81cbd1fff1bdc54c00728e

%gometa

%global common_description %{expand:
Go library to get the browser and OS from the User-Agent header.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go library to get the browser and OS from the User-Agent header

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:12:07 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809git6441213
- Initial package

