# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zli
%global goipath         zgo.at/zli
%global forgeurl        https://github.com/zgoat/zli
%global commit          d9fa18baab0f226c009890e753d1a53c02f3e8ee

%gometa

%global common_description %{expand:
A Go library for writing CLI programs. It includes flag parsing, colour escape
codes, and various helpful utility functions, and makes testing fairly easy.}

%global golicenses      LICENSE
%global godocs          README.markdown flag.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Go library for writing CLI programs. It includes flag parsing, colour escape codes, and various helpful utility functions, and makes testing fairly easy

# Upstream license specification: MIT and BSD-3-Clause
License:        MIT and BSD
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.markdown flag.markdown
%{_bindir}/*

%gopkgfiles

%changelog
* Fri Aug 28 16:37:51 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200828gitd9fa18b
- Initial package

