# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zdb
%global goipath         zgo.at/zdb
%global forgeurl        https://github.com/zgoat/zdb
%global commit          36a119a21b96574f819d62690f21d88f5294e1dc

%gometa

%global common_description %{expand:
Go database stuff.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go database stuff

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/jmoiron/sqlx)
BuildRequires:  golang(github.com/lib/pq)
BuildRequires:  golang(github.com/mattn/go-sqlite3)
BuildRequires:  golang(zgo.at/zlog)
BuildRequires:  golang(zgo.at/zstd/zbyte)
BuildRequires:  golang(zgo.at/zstd/zfloat)
BuildRequires:  golang(zgo.at/zstd/zint)
BuildRequires:  golang(zgo.at/zstd/zstring)

%if %{with check}
# Tests
BuildRequires:  golang(zgo.at/zstd/ztest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Sep 19 16:47:36 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200919git36a119a
- Initial package

