# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zhttp
%global goipath         zgo.at/zhttp
%global forgeurl        https://github.com/zgoat/zhttp
%global commit          46429e444027ee3bb0012b8f2cf1e87f0b60543b

%gometa

%global common_description %{expand:
Martin's HTTP package.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Martin's HTTP package

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(github.com/monoculum/formam)
BuildRequires:  golang(zgo.at/guru)
BuildRequires:  golang(zgo.at/json)
BuildRequires:  golang(zgo.at/zlog)
BuildRequires:  golang(zgo.at/zstd/ztime)

%if %{with check}
# Tests
BuildRequires:  golang(zgo.at/zstd/ztest)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:07:06 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809git46429e4
- Initial package

