# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zstd
%global goipath         zgo.at/zstd
%global forgeurl        https://github.com/zgoat/zstd
%global commit          59bd1cd930f3d35925773205822b73ccf1a48c83

%gometa

%global common_description %{expand:
A collection of extensions to Go's standard library.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A collection of extensions to Go's standard library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Wed Sep 09 08:55:52 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200909git59bd1cd
- Initial package

