# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/zgoat/zstd
%global goipath         zgo.at/zstd
%global forgeurl        https://github.com/zgoat/zstd
%global commit          a4927f23388f32342e53b0ac0cedf7ef4b452047

%gometa

%global common_description %{expand:
Extensions to Go's stdlib.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Extensions to Go's stdlib

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Fri Jun 25 09:01:27 CEST 2021 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20210625gita4927f2
- Initial package

