# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/monoculum/formam
%global goipath         github.com/monoculum/formam
Version:                3.5.0

%gometa

%global common_description %{expand:
A package for decode form's values into struct in Go.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        A package for decode form's values into struct in Go

# Upstream license specification: Apache-2.0
License:        ASL 2.0
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Oct 31 11:37:19 CET 2020 Johan Kok <johankok@users.noreply.github.com> - 3.5.0-1
- Bumped to version 3.5.0

* Sun Aug 09 11:31:14 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 3.3.0-1
- Initial package

