# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/blackmail
%global goipath         zgo.at/blackmail
%global forgeurl        https://github.com/zgoat/blackmail
%global commit          f1e44ef1dbb893804c088108faa00f340ff6414b

%gometa

%global common_description %{expand:
Go package to send emails with a friendly API and PGP signing.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go package to send emails with a friendly API and PGP signing

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/crypto/openpgp)
BuildRequires:  golang(golang.org/x/crypto/openpgp/armor)
BuildRequires:  golang(golang.org/x/crypto/openpgp/packet)

%if %{with check}
# Tests
BuildRequires:  golang(zgo.at/ztest)
BuildRequires:  golang(zgo.at/ztest/image)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.markdown
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Aug 09 11:11:37 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809gitf1e44ef
- Initial package

