# Generated by go2rpm 1.6.0
%bcond_without check

# https://github.com/arp242/isbot
%global goipath         zgo.at/isbot
%global forgeurl        https://github.com/arp242/isbot
Version:                1.0.0

%gometa

%global common_description %{expand:
Go library to detect HTTP bots.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go library to detect HTTP bots

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Fri May 20 2022 Johan Kok <johankok@users.noreply.github.com> - 1.0.0-1
- Initial package
