# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/zgoat/isbot
%global goipath         zgo.at/isbot
%global forgeurl        https://github.com/zgoat/isbot
%global commit          22da657c7bcf1ef2fe0a4a329ff921dc595e57e4

%gometa

%global common_description %{expand:
Go library to detect HTTP bots.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go library to detect HTTP bots

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Oct 31 11:30:04 CET 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20201031git22da657
- Initial package

