# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/tz
%global goipath         zgo.at/tz
%global forgeurl        https://github.com/zgoat/tz
%global commit          aeba38d94d93fb50cc09da5a29e110c5520fac01

%gometa

%global common_description %{expand:
Go timezone convience library.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go timezone convience library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%build
%gobuild -o %{gobuilddir}/bin/tz %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.markdown
%{_bindir}/*

%gopkgfiles

%changelog
* Sun Aug 09 11:12:51 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809gitaeba38d
- Initial package

