# Generated by go2rpm 1
%bcond_without check

# https://github.com/arp242/maxminddb-golang
%global goipath         github.com/arp242/maxminddb-golang
Version:                1.6.0

%gometa

%global common_description %{expand:
MaxMind DB Reader for Go.}

%global golicenses      LICENSE test-data/LICENSE
%global godocs          README.md test-data/MaxMind-DB-spec.md test-\\\
                        data/README.md test-data/bad-data/README.md test-\\\
                        data/source-data/README test-data/test-data/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        MaxMind DB Reader for Go

License:        ISC
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:42:29 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 1.6.0-1
- Initial package

