# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zstripe
%global goipath         zgo.at/zstripe
%global forgeurl        https://github.com/zgoat/zstripe
Version:                1.0.0

%gometa

%global common_description %{expand:
Set of utility functions for working with the Stripe API.}

%global godocs          README.markdown

Name:           %{goname}
Release:        1%{?dist}
Summary:        Set of utility functions for working with the Stripe API

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:01:23 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 1.0.0-1
- Initial package

