# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/dominikh/go-tools
%global goipath         honnef.co/go/tools
%global forgeurl        https://github.com/dominikh/go-tools
Version:                2020.1.6

%gometa

%global common_description %{expand:
Staticcheck - The advanced Go linter.}

%global golicenses      LICENSE LICENSE-THIRD-PARTY lint/LICENSE\\\
                        gcsizes/LICENSE ir/LICENSE
%global godocs          doc README.md cmd/keyify/README.md\\\
                        cmd/rdeps/README.md cmd/staticcheck/README.md\\\
                        cmd/structlayout/README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Staticcheck - The advanced Go linter

# Upstream license specification: MIT and BSD-3-Clause
License:        MIT and BSD
URL:            %{gourl}
Source0:        %{forgeurl}/archive/%{version}.tar.gz

BuildRequires:  golang(github.com/BurntSushi/toml)
BuildRequires:  golang(github.com/google/renameio)
BuildRequires:  golang(github.com/kisielk/gotool)
BuildRequires:  golang(github.com/rogpeppe/go-internal/modfile)
BuildRequires:  golang(golang.org/x/mod/module)
BuildRequires:  golang(golang.org/x/tools/go/analysis)
BuildRequires:  golang(golang.org/x/tools/go/analysis/analysistest)
BuildRequires:  golang(golang.org/x/tools/go/analysis/passes/inspect)
BuildRequires:  golang(golang.org/x/tools/go/ast/astutil)
BuildRequires:  golang(golang.org/x/tools/go/ast/inspector)
BuildRequires:  golang(golang.org/x/tools/go/buildutil)
BuildRequires:  golang(golang.org/x/tools/go/gcexportdata)
BuildRequires:  golang(golang.org/x/tools/go/loader)
BuildRequires:  golang(golang.org/x/tools/go/packages)
BuildRequires:  golang(golang.org/x/tools/go/types/objectpath)
BuildRequires:  golang(golang.org/x/tools/go/types/typeutil)
BuildRequires:  golang(golang.org/x/tools/refactor/importgraph)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
for cmd in ir ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE LICENSE-THIRD-PARTY lint/LICENSE gcsizes/LICENSE ir/LICENSE
%doc doc README.md cmd/keyify/README.md cmd/rdeps/README.md
%doc cmd/staticcheck/README.md cmd/structlayout/README.md
%{_bindir}/*

%gopkgfiles

%changelog
* Sat Oct 31 11:44:02 CET 2020 Johan Kok <johankok@users.noreply.github.com> - 0.0.1-2020.1.6-1
- Bumped to version 2020.1.6

* Sun Aug 09 12:38:43 CEST 2020 Johan Kok <johan@fedoraproject.org> - 0.0.1-2020.1.5-1
- Initial package

