# Generated by go2rpm 1.3
%bcond_without check

# https://github.com/zgoat/zli
%global goipath         zgo.at/zli
%global forgeurl        https://github.com/zgoat/zli
%global commit          d03e49b7c9eaee2c71ac1f9d53abb71588b0dabc

%gometa

%global common_description %{expand:
A Go library for writing CLI programs. It includes flag parsing, colour escape
codes, and various helpful utility functions, and makes testing fairly easy.}

%global golicenses      LICENSE
%global godocs          README.markdown flag.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        A Go library for writing CLI programs. It includes flag parsing, colour escape codes, and various helpful utility functions, and makes testing fairly easy

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

BuildRequires:  golang(golang.org/x/term)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.markdown flag.markdown
%{_bindir}/*

%gopkgfiles

%changelog
* Fri Jun 25 08:58:24 CEST 2021 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20210625gitd03e49b
- Initial package

