# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/json
%global goipath         zgo.at/json
%global forgeurl        https://github.com/zgoat/json
%global commit          d5025253667f88915f22bb8d1a456025b921a30a

%gometa

%global common_description %{expand:
Encoding/json with patches.}

%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Encoding/json with patches

License:        # FIXME

URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:28:40 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809gitd502525
- Initial package

