# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zlog
%global goipath         zgo.at/zlog
%global forgeurl        https://github.com/zgoat/zlog
%global commit          2326f63c8cfaf1ec73ce2514aa76fe6aeb9d7bcd

%gometa

%global common_description %{expand:
Go logging library.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go logging library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:04:48 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200809git2326f63
- Initial package

