# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/zlog
%global goipath         zgo.at/zlog
%global forgeurl        https://github.com/zgoat/zlog
%global commit          6d07ccc4c7cf1ffd6e46818c63b75314a9e34551

%gometa

%global common_description %{expand:
Go logging library.}

%global golicenses      LICENSE
%global godocs          README.markdown

Name:           %{goname}
Version:        0
Release:        0.1%{?dist}
Summary:        Go logging library

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sat Sep 19 16:46:17 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 0-0.1.20200919git6d07ccc
- Initial package

