# Generated by go2rpm 1
%bcond_without check

# https://github.com/zgoat/guru
%global goipath         zgo.at/guru
%global forgeurl        https://github.com/zgoat/guru
Version:                1.1.0

%gometa

%global common_description %{expand:
Go errors with a Guru Meditation Number.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        Go errors with a Guru Meditation Number

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Sun Aug 09 11:12:23 CEST 2020 Johan Kok <johankok@users.noreply.github.com> - 1.1.0-1
- Initial package

